// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySybm4U02Cp4QwNXHyI5hRJShJIw0GU4',
    appId: '1:346029450305:web:a7175ff3db422cb5e252c0',
    messagingSenderId: '346029450305',
    projectId: 'music-app-8974d',
    authDomain: 'music-app-8974d.firebaseapp.com',
    storageBucket: 'music-app-8974d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0FHwmV-29H6HQJtFuJdh-Y-lsj0YbKU',
    appId: '1:346029450305:android:575a5bb0f0a3a832e252c0',
    messagingSenderId: '346029450305',
    projectId: 'music-app-8974d',
    storageBucket: 'music-app-8974d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0xTrDH-bxUOJEO2pBKiVw3MYSUEt37TA',
    appId: '1:346029450305:ios:6848ecb29bb0b1dfe252c0',
    messagingSenderId: '346029450305',
    projectId: 'music-app-8974d',
    storageBucket: 'music-app-8974d.appspot.com',
    iosClientId: '346029450305-05v20pgsg5o92bmc61jag6ntmdvil2j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0xTrDH-bxUOJEO2pBKiVw3MYSUEt37TA',
    appId: '1:346029450305:ios:6848ecb29bb0b1dfe252c0',
    messagingSenderId: '346029450305',
    projectId: 'music-app-8974d',
    storageBucket: 'music-app-8974d.appspot.com',
    iosClientId: '346029450305-05v20pgsg5o92bmc61jag6ntmdvil2j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );
}
